/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate with email + password and return a session cookie.
         *
         *     On success: creates a server-side session row and sets the ``HttpOnly``
         *     session cookie.  Returns the public user object.
         *
         *     On failure: returns 401 (email not found or wrong password).  The same
         *     error is returned for both cases to prevent user-enumeration attacks.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the current session and clear the cookie.
         *
         *     Idempotent: if the cookie is absent or the session is already gone, the
         *     endpoint still returns 200 and clears the cookie.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the currently authenticated user.
         *
         *     Requires a valid session cookie.  Returns 401 if absent / expired.
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Setup
         * @description Create the first admin user (first-run onboarding).
         *
         *     Self-closing and concurrency-safe: the admin user and a sentinel row
         *     (``app_config.key = 'onboarding_completed'``) are created in a **single
         *     transaction**.  Because ``app_config.key`` is the primary key, a second
         *     concurrent request that also passes the fast-path pre-check will hit a
         *     primary-key ``IntegrityError`` when it tries to insert the same sentinel,
         *     causing its transaction to roll back → 409.
         *
         *     This works even when two concurrent requests each read ``count == 0`` with
         *     *different* emails (which would bypass the email-unique constraint alone):
         *     only one can win the sentinel insert; the loser always gets 409.
         *
         *     Fast-path pre-check (sentinel exists or any user exists → 409) is kept for
         *     the common case, but the correctness guarantee comes from the unique-key
         *     sentinel insert, not from the pre-check.
         *
         *     On success returns the created user (HTTP 201).  Does NOT auto-login —
         *     the frontend transitions to the normal login screen after setup.
         */
        post: operations["setup_api_auth_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/setup-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Setup Status
         * @description Return whether first-run setup is still required.
         *
         *     ``setup_required: true``  — no users exist; the setup page must be shown.
         *     ``setup_required: false`` — at least one user exists; show the login page.
         *
         *     Unauthenticated — the frontend calls this on every load to decide which
         *     page to show before the user has any session cookie.
         */
        get: operations["setup_status_api_auth_setup_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Return service health.
         *
         *     ``status``      always ``"ok"`` while the process is running.
         *     ``version``     application release version.
         *     ``api_version`` integer compatibility number from Settings.
         *     ``db``          ``"ok"`` if ``SELECT 1`` succeeds; propagates exception
         *                     on DB failure (FastAPI returns 500).
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Shape of the /health response (Step 3+).
         */
        HealthResponse: {
            /** Api Version */
            api_version: number;
            /** Db */
            db: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * LoginRequest
         * @description Body for POST /auth/login.
         */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MeResponse
         * @description Response body for GET /auth/me.
         */
        MeResponse: {
            user: components["schemas"]["UserResponse"];
        };
        /**
         * MessageResponse
         * @description Generic message response (used for logout).
         */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /**
         * SetupRequest
         * @description Body for POST /auth/setup — create the first admin user.
         */
        SetupRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * SetupStatusResponse
         * @description Response body for GET /auth/setup-status.
         */
        SetupStatusResponse: {
            /** Setup Required */
            setup_required: boolean;
        };
        /**
         * UserResponse
         * @description Public representation of a User (no password_hash).
         */
        UserResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Role */
            role: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    setup_api_auth_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    setup_status_api_auth_setup_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusResponse"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
